# Generated by Django 4.0 on 2022-01-02 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_categories_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 22, 54, 40, 889052, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
