# Generated by Django 4.0 on 2022-01-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenas',
            name='star',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stars'),
        ),
    ]
